version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rootgzy
      POSTGRES_USER: rootgzy
      POSTGRES_PASSWORD: rootgzy
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      SMTP_HOST: sandbox.smtp.mailtrap.io
      SMTP_PORT: 587
      SMTP_USERNAME: 5c1926371f9c05
      SMTP_PASSWORD: 03fa6ca24d4367
